### ISSUE TITLE
Doesn't work well for large files and minified fields

### ISSUE THREAD

**Issue by fresheneesz** [sokra/source-map-visualization#11]
First of all, I love this tool. But I'm trying to use this tool to view my webpack bundle to verify how its sourcemap is working in a specific part, and the three boxes can't be seen all at once. Not only that, but the minified bundle is only two incredibly long lines, so highlighting anything in any box basically shows me nothing. 

I suggest the following:
A. Make the boxes float side-by-side so you can always see all 3 boxes at the same time like they do in this viewer: http://sourcemapper.qfox.nl/
B. Make each box only the height of the page, so that you can see the *whole* box for each
C. When you highlight a segment, scroll to the corresponding segements in the other two boxes

Is this doable?

**Comment by sokra** [comment]
> Is this doable?

I think so... Do you want to do a PR?

**Comment by fresheneesz** [comment]
I feel like I could do a PR, but I don't have the time right now : / . Already have a couple other PRs on my plate I need to get to first.

**Comment by sokra** [comment]
> but I don't have the time right now

I have the same problem...

**Comment by paulirish** [comment]
fwiw: I have work inside of https://github.com/sokra/source-map-visualization/pull/16 which partially fixes these concerns.

**Comment by sokra** [comment]
Made a few changes and it should be more performant and better readable now.

**Comment by paulirish** [comment]
Tried out a few more changes along these lines. 3 independently scrolling panes.

branch: https://github.com/paulirish/source-map-visualization/tree/applayout

demo: http://paulirish.github.io/source-map-visualization/#babel

![image](https://cloud.githubusercontent.com/assets/39191/14974184/794a4e0e-10a6-11e6-94f3-2beb1cd3488b.png)
