### ISSUE TITLE
Custom import fails when map file has a sourcesContent property set to an empty array

### ISSUE THREAD

**Issue by SeinopSys** [sokra/source-map-visualization#12]
I'm using [node-sass](https://github.com/sass/node-sass) and it automatically adds a `sourcesContent` key with an empty array as its value, which fools the app, and instead of asking for missing source files, it just says that they cannot be found.

To reproduce, add

```
sourcesContent: [],
```

to any valid map file and try to get to the 3rd import step. The import will fail.

**Comment by paulirish** [comment]
fixed in node-sass.
https://github.com/sass/node-sass/issues/1045#issuecomment-167376744
