### ISSUE TITLE
CLI tool for super quick visualizations

### ISSUE THREAD

**Issue by lydell** [sokra/source-map-visualization#13]
Hi! I just made a [CLI tool](https://github.com/lydell/source-map-visualize) to easily use your visualizer with local files without having to go through all the steps of uploading the files.

    $ source-map-visualize generated.js

Boom! The visualizer opens in your default browser with all the files pre-loaded. Enjoy!

**Comment by sokra** [comment]
Nice...

**Comment by JordanMartinez** [comment]
Does this tool still work?

**Comment by paulirish** [comment]
[source-map-visualization](https://github.com/sokra/source-map-visualization) does still work but tbh i would recommend using https://evanw.github.io/source-map-visualization/ instead at this point.

**Comment by abitrolly** [comment]
@paulirish unclear license in https://github.com/evanw/source-map-visualization/ and no synchronized scrolling between pages. Although this project doesn't have the sync too.

**Comment by JordanMartinez** [comment]
To clarify, I was referring to the `source-map-visualize` CLI tool.

And I can't use the `evanw` one as it only supports 2 files, not three.
