### ISSUE TITLE
Strip XSSI prefix

### ISSUE THREAD

**Issue by DavidSouther** [sokra/source-map-visualization#9]
The sourcemap spec encourages `)]}` as a prefix for XSSI prevention. This should be stripped before parsing custom sourcemaps, when present.

https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.h7yy76c5il9v

**Comment by lydell** [comment]
Are you sure this is not done? This tool depends on the mozilla/source-map module, which [strips it](https://github.com/mozilla/source-map/blob/d55e947a5845c94a8781bc82b456d1f362ce98b2/lib/source-map/source-map-consumer.js#L21).

**Comment by paulirish** [comment]
fixed by #25
